from dotenv import load_dotenv
load_dotenv()
import pandas as pd
import io
from source_code.graph import ds_machine
from source_code.utils import classify_columns, build_value_counts_summary, build_null_summary


def run_pipeline():
    file_path = r"data/telecom_churn_data.csv" 
    # ── Your SQL query and special rules about dataset ────────────────
    with open(r"queries/churn_query.sql", "r", encoding="utf-8") as f:
        sql_query = f.read()
    with open(r"rules/special_rules.txt", "r", encoding="utf-8") as f:
        special_rules = f.read()

    # ── Extract metadata  ────────────────────────────────────
    print("1. Loading dataset and extracting metadata...")
    df = pd.read_csv(file_path)
    dtypes_dict = df.dtypes.astype(str).to_dict() # 1. dictionary of column names and their data types
    sample_row = df.head(1).to_dict(orient='records')[0] # 2. Grab just ONE row
    # Combine into a string
    dynamic_metadata = f"""
                            DATASET PROFILE:
                            1. COLUMNS & TYPES:
                            {dtypes_dict}
                            2. SAMPLE ROW:
                            {sample_row}
                        """

    print("Metadata extracted. Passing to the AI...")
    
    # ── Column classification (for Agent 2 cleaning) ─────────────────────────────
    print("2. Classifying columns and building enriched metadata...")
    categorical_cols, numeric_like_cols, true_numeric_cols = classify_columns(df)
    value_counts_summary = build_value_counts_summary(df, categorical_cols, top_n=20)
    null_summary = build_null_summary(df)

    print(f"   Categorical : {len(categorical_cols)} columns")
    print(f"   Numeric-like (dirty): {len(numeric_like_cols)} columns → {numeric_like_cols}")
    print(f"   True numeric: {len(true_numeric_cols)} columns")


    # ── Build initial state ──────────────────────────────────────────────────────
    initial_input = {
        "file_path"            : file_path,
        "target_column"        : "ChurnFlag",
        "sql_query"            : sql_query,
        "df_columns"           : list(df.columns),
        "special_rules"        : special_rules,
        "iteration_count"      : 0,

        # Metadata for Agent 1 (Renaming Columns)
        "metadata_summary"     : dynamic_metadata,

        # Enriched metadata for Agent 2 (cleaning)
        "categorical_cols"     : categorical_cols,
        "numeric_like_cols"    : numeric_like_cols,
        "true_numeric_cols"    : true_numeric_cols,
        "value_counts_summary" : value_counts_summary,
        "null_summary"         : null_summary,
    }

    print()
    print("2. Starting the DS Machine...\n")

    for output in ds_machine.stream(initial_input): # type: ignore
        for node_name, state_updates in output.items():
            if "cleaning_code" in state_updates:
                print(f"CODE GENERATED BY [{node_name}]")
                print(state_updates['cleaning_code'])
            
            if "ambiguous_fields" in state_updates: # Surfaces ambiguous field names inline during streaming
                ambiguous = state_updates["ambiguous_fields"]
                if ambiguous:
                    print()
                    print(f"AMBIGUOUS FIELDS FLAGGED BY {node_name} — Review needed:")
                    for field in ambiguous:
                        print(f"  - {field.get('original_column')} → candidates: {field.get('candidates')}")
                        print(f"    reason: {field.get('reason')}\n")
                        
            if "flagged_columns" in state_updates: #
                flagged = state_updates["flagged_columns"]
                if flagged:
                    print(f"\n🚩 FLAGGED COLUMNS — {node_name.upper()}:")
                    for f in flagged:
                        print(f"  - {f.get('column')} | reason: {f.get('reason')}")


if __name__ == "__main__":
    run_pipeline()