from dotenv import load_dotenv
load_dotenv()
from source_code.config.llm_config import PipelineConfig
from source_code.config.loaders import load_pipeline_inputs
from source_code.graph import build_graph


def run_pipeline():
    """
    Entry point for the DS Machine pipeline.
    Loads inputs via load_pipeline_inputs, builds graph from env config,
    streams execution, and prints output to console.
    """
    initial_input = load_pipeline_inputs(
        data_path     = r"data/telecom_churn_data.csv",
        query_path    = r"queries/churn_query.sql",
        rules_path    = r"rules/special_rules.txt",
        target_column = "ChurnFlag",    # [AUDIT M10]
    )

    config = PipelineConfig.from_env()
    ds_machine = build_graph(config)

    print()
    print("2. Starting the DS Machine...\n")

    for output in ds_machine.stream(initial_input):  # type: ignore
        for node_name, state_updates in output.items():
            if "cleaning_code" in state_updates:
                print(f"CODE GENERATED BY [{node_name}]")
                print(state_updates['cleaning_code'])

            if "ambiguous_fields" in state_updates:  # Surfaces ambiguous field names inline during streaming
                ambiguous = state_updates["ambiguous_fields"]
                if ambiguous:
                    print()
                    print(f"AMBIGUOUS FIELDS FLAGGED BY {node_name} — Review needed:")
                    for field in ambiguous:
                        print(f"  - {field.get('original_column')} -> candidates: {field.get('candidates')}")
                        print(f"    reason: {field.get('reason')}\n")

            if "flagged_columns" in state_updates:
                flagged = state_updates["flagged_columns"]
                if flagged:
                    print(f"\nFLAGGED COLUMNS — {node_name.upper()}:")
                    for f in flagged:
                        print(f"  - {f.get('column')} | reason: {f.get('reason')}")


if __name__ == "__main__":
    run_pipeline()
